# Generated by Django 5.0.4 on 2024-05-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meal_type', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack')], default='breakfast', max_length=10)),
                ('date', models.DateTimeField()),
                ('products', models.ManyToManyField(related_name='meals', to='products.product')),
            ],
        ),
    ]
