# Generated by Django 5.0.4 on 2024-05-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='date',
        ),
    ]
