# Generated by Django 5.0.4 on 2024-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_meal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals', models.ManyToManyField(to='meals.meal')),
            ],
        ),
    ]
