# Generated by Django 5.0.4 on 2024-05-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_delete_mealdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.CreateModel(
            name='MealOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner'), ('snack', 'snack')], default='breakfast', max_length=10)),
                ('meals', models.ManyToManyField(to='meals.meal')),
            ],
        ),
    ]
