# Generated by Django 5.0.4 on 2024-05-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Planner',
        ),
    ]
